[package]
name = "rust-openai-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.18.2"
serde_json = "1.0.108"
tokio = { version = "1.25.0", features = ["full"] }
